### ISSUE TITLE
Include the required properties for Mail Destinations

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-connectivity#3]
### Issue description

Step 6 states: "Optional: You can enter additional properties."

Mail Destinations have mandatory "additional" properties that have to be filled. It would be nice to include those here in the documentation.

E.g.:

- mail.smtp.host
- mail.smtp.port
- mail.user
- mail.password

E.g. when you use the destination via the SAP Cloud SDK - which should link to this page - see https://github.com/SAP/cloud-sdk/issues/1709.

Kind regards,
Sebastian

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Create Mail Destinations

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/create-mail-destinations?version=Cloud

**Comment by Frank1Mueller** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Frank1Mueller** [comment]
Thanks again for you feedback, Sebastian. 

This is definitely a good point.

Before updating the documentation, I'd like to discuss some details:

From my perspective, only the first parameter in your list (mail.smtp.host) is a mandatory "additional" parameter. mail.smtp.port might use the smtp standard port if not defined. mail.user and mail.password are actually not "additional" parameters, but standard parameters, and only required if you use authentication type "Basic Authentication".

Do you agree with this definition?

Best regards

Frank

**Comment by sebastianesch** [comment]
I agree with the definition, but they go into the "additional" properties of the destination. :)

From my point of view, the documentation currently does not explain which properties are required for different scenarios. I had to step trough the Cloud SDK mail client in the debugger to figure out how to setup the destination.

Kind regards,
Sebastian

**Comment by Frank1Mueller** [comment]
Hi Sebastian,

thanks a lot for your reply. 

Yes, you're definitely right. Some properties are listed as "additional", though being present as standard properties in the relevant scenarios. This is a known inconsistency that unfortunately cannot be solved completely by just updating the documentation. However, the dev colleagues are currently working on a new version of the destinations editor that includes an improved "additional properties" section.
For now, regarding the different destination scenarios (in terms of "authentication types used") I will add the parameter mail.smtp.host as mandatory property in documentation, because in fact it is (regardless of the scenario used), and should actually be a standard parameter.
I hope this will help at least a little bit for the time being.
